
FT_DPCM_PTR=$c000
	.export _music_data
;this file for FamiTone2 library generated by text2data tool
_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $70 ;instrument $02
	.word @env1,@env3,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env2,@env0,@env0
	.byte $00
	.byte $70 ;instrument $04
	.word @env1,@env4,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cc,$c9,$c8,$c5,$c4,$c2,$c3,$02,$c2,$03,$c2,$00,$0a
@env2:
	.byte $cc,$ca,$c8,$c6,$c4,$c2,$c0,$00,$06
@env3:
	.byte $c0,$c1,$c0,$00,$02
@env4:
	.byte $c0,$c0,$c3,$c3,$c7,$c7,$c0,$c0,$00,$00


@song0ch0:
	.byte $fb,$04
@song0ch0loop:
@ref0:
	.byte $80,$33,$35,$33,$35,$33,$35,$33,$35,$33,$35,$33,$35,$33,$35,$33
	.byte $34,$81
@ref1:
	.byte $3d,$33,$3d,$33,$3d,$33,$3d,$33,$3d,$33,$3d,$33,$3d,$33,$3d,$32
	.byte $81
@ref2:
	.byte $41,$3d,$41,$3d,$41,$3d,$41,$3d,$41,$3d,$41,$3d,$41,$3d,$41,$3c
	.byte $81
@ref3:
	.byte $84,$40,$bd
	.byte $ff,$11
	.word @ref0
	.byte $ff,$11
	.word @ref1
	.byte $ff,$11
	.word @ref2
@ref7:
	.byte $84,$40,$bd
@ref8:
	.byte $82,$32,$85,$40,$85,$3e,$85,$38,$85,$32,$85,$34,$8d,$32,$85
@ref9:
	.byte $87,$28,$8d,$28,$85,$2a,$85,$28,$85,$26,$85,$20,$85
@ref10:
	.byte $32,$85,$40,$85,$3e,$85,$38,$85,$32,$85,$34,$8d,$32,$85
@ref11:
	.byte $8f,$1b,$29,$1b,$29,$1d,$27,$1d,$27,$1b,$29,$1b,$28,$81
@ref12:
	.byte $2f,$39,$2f,$39,$29,$37,$29,$37,$2f,$39,$2f,$39,$29,$37,$29,$36
	.byte $81
@ref13:
	.byte $37,$39,$37,$39,$33,$37,$33,$37,$37,$39,$37,$39,$33,$37,$33,$84
	.byte $36,$81
@ref14:
	.byte $bf
@ref15:
	.byte $bf
@ref16:
	.byte $82,$4a,$85,$58,$85,$56,$85,$50,$85,$4a,$85,$4c,$8d,$4a,$85
@ref17:
	.byte $87,$40,$8d,$40,$85,$42,$85,$40,$85,$3e,$85,$38,$85
@ref18:
	.byte $4a,$85,$58,$85,$56,$85,$50,$85,$4a,$85,$4c,$8d,$4a,$85
@ref19:
	.byte $8f,$32,$85,$32,$85,$36,$85,$36,$85,$38,$85,$38,$85
	.byte $ff,$11
	.word @ref12
	.byte $ff,$11
	.word @ref13
@ref22:
	.byte $bf
@ref23:
	.byte $bf
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref24:
	.byte $82,$32,$85,$33,$33,$34,$85,$32,$85,$2e,$85,$32,$85,$2a,$85,$2e
	.byte $85
@ref25:
	.byte $1a,$85,$1b,$1b,$1c,$85,$1a,$85,$16,$85,$1a,$85,$12,$85,$16,$85
@ref26:
	.byte $32,$85,$33,$33,$34,$85,$32,$85,$2e,$85,$32,$85,$2a,$85,$2e,$85
@ref27:
	.byte $1a,$85,$1a,$85,$1a,$8d,$1a,$85,$1a,$85,$1a,$8d
@ref28:
	.byte $4a,$85,$4b,$4b,$4c,$85,$4a,$85,$46,$85,$4a,$85,$42,$85,$46,$85
	.byte $ff,$10
	.word @ref26
	.byte $ff,$10
	.word @ref28
@ref31:
	.byte $32,$85,$32,$85,$32,$8d,$32,$85,$32,$85,$32,$8d
@ref32:
	.byte $4b,$51,$59,$51,$4b,$51,$59,$51,$4b,$51,$59,$51,$4b,$51,$59,$50
	.byte $81
	.byte $ff,$11
	.word @ref32
	.byte $ff,$11
	.word @ref32
@ref35:
	.byte $4b,$51,$59,$51,$71,$51,$59,$51,$67,$51,$59,$51,$69,$51,$59,$50
	.byte $81
@ref36:
	.byte $4a,$9d,$51,$59,$50,$85,$4e,$8d
@ref37:
	.byte $4e,$9d,$39,$41,$38,$85,$36,$8d
@ref38:
	.byte $bf
@ref39:
	.byte $bf
	.byte $ff,$11
	.word @ref32
	.byte $ff,$11
	.word @ref32
	.byte $ff,$11
	.word @ref32
	.byte $ff,$11
	.word @ref35
	.byte $ff,$08
	.word @ref36
	.byte $ff,$08
	.word @ref37
@ref46:
	.byte $bf
@ref47:
	.byte $bf
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref48:
	.byte $80,$32,$85,$33,$33,$34,$85,$32,$85,$2e,$85,$32,$85,$2a,$85,$2e
	.byte $85
	.byte $ff,$10
	.word @ref25
	.byte $ff,$10
	.word @ref26
	.byte $ff,$0c
	.word @ref27
	.byte $ff,$10
	.word @ref26
	.byte $ff,$10
	.word @ref25
	.byte $ff,$10
	.word @ref26
	.byte $ff,$0c
	.word @ref27
@ref56:
	.byte $32,$95,$32,$8d,$32,$8d,$32,$85
	.byte $ff,$08
	.word @ref56
	.byte $ff,$08
	.word @ref56
@ref59:
	.byte $32,$95,$32,$85,$32,$9d
@ref60:
	.byte $42,$85,$42,$85,$46,$85,$42,$85,$4a,$85,$42,$8d,$43,$46,$81
@ref61:
	.byte $5a,$85,$5a,$85,$5e,$85,$5a,$85,$62,$85,$5a,$8d,$43,$84,$2e,$81
@ref62:
	.byte $bf
@ref63:
	.byte $bf
@ref64:
	.byte $80,$32,$95,$32,$8d,$32,$8d,$32,$85
	.byte $ff,$08
	.word @ref56
	.byte $ff,$08
	.word @ref56
	.byte $ff,$06
	.word @ref59
	.byte $ff,$0f
	.word @ref60
	.byte $ff,$0f
	.word @ref61
@ref70:
	.byte $bf
@ref71:
	.byte $bf
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref72:
	.byte $82,$04,$85,$1f,$1f,$12,$85,$1f,$1f,$04,$85,$1f,$1f,$12,$85,$1f
	.byte $1e,$81
@ref73:
	.byte $04,$85,$1f,$1f,$12,$85,$1f,$1f,$04,$85,$1f,$1f,$12,$85,$1f,$1e
	.byte $81
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref96:
	.byte $bf
@ref97:
	.byte $bf
@ref98:
	.byte $bf
@ref99:
	.byte $bf
@ref100:
	.byte $bf
@ref101:
	.byte $bf
@ref102:
	.byte $bf
@ref103:
	.byte $bf
@ref104:
	.byte $bf
@ref105:
	.byte $bf
@ref106:
	.byte $bf
@ref107:
	.byte $bf
@ref108:
	.byte $bf
@ref109:
	.byte $bf
@ref110:
	.byte $bf
@ref111:
	.byte $bf
@ref112:
	.byte $bf
@ref113:
	.byte $bf
@ref114:
	.byte $bf
@ref115:
	.byte $bf
@ref116:
	.byte $bf
@ref117:
	.byte $bf
@ref118:
	.byte $bf
@ref119:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$03
@song1ch0loop:
	.byte $ff,$11
	.word @ref0
	.byte $ff,$11
	.word @ref1
	.byte $ff,$11
	.word @ref2
@ref123:
	.byte $84,$40,$bd
	.byte $ff,$11
	.word @ref0
	.byte $ff,$11
	.word @ref1
	.byte $ff,$11
	.word @ref2
@ref127:
	.byte $84,$40,$bd
	.byte $ff,$0e
	.word @ref8
	.byte $ff,$0d
	.word @ref9
	.byte $ff,$0e
	.word @ref10
	.byte $ff,$0e
	.word @ref11
	.byte $ff,$11
	.word @ref12
	.byte $ff,$11
	.word @ref13
@ref134:
	.byte $bf
@ref135:
	.byte $bf
	.byte $ff,$0e
	.word @ref16
	.byte $ff,$0d
	.word @ref17
	.byte $ff,$0e
	.word @ref18
	.byte $ff,$0d
	.word @ref19
	.byte $ff,$11
	.word @ref12
	.byte $ff,$11
	.word @ref13
@ref142:
	.byte $bf
@ref143:
	.byte $bf
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
	.byte $ff,$10
	.word @ref24
	.byte $ff,$10
	.word @ref25
	.byte $ff,$10
	.word @ref26
	.byte $ff,$0c
	.word @ref27
	.byte $ff,$10
	.word @ref28
	.byte $ff,$10
	.word @ref26
	.byte $ff,$10
	.word @ref28
	.byte $ff,$0c
	.word @ref31
	.byte $ff,$11
	.word @ref32
	.byte $ff,$11
	.word @ref32
	.byte $ff,$11
	.word @ref32
	.byte $ff,$11
	.word @ref35
	.byte $ff,$08
	.word @ref36
	.byte $ff,$08
	.word @ref37
@ref158:
	.byte $bf
@ref159:
	.byte $bf
	.byte $ff,$11
	.word @ref32
	.byte $ff,$11
	.word @ref32
	.byte $ff,$11
	.word @ref32
	.byte $ff,$11
	.word @ref35
	.byte $ff,$08
	.word @ref36
	.byte $ff,$08
	.word @ref37
@ref166:
	.byte $bf
@ref167:
	.byte $bf
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
	.byte $ff,$10
	.word @ref48
	.byte $ff,$10
	.word @ref25
	.byte $ff,$10
	.word @ref26
	.byte $ff,$0c
	.word @ref27
	.byte $ff,$10
	.word @ref26
	.byte $ff,$10
	.word @ref25
	.byte $ff,$10
	.word @ref26
	.byte $ff,$0c
	.word @ref27
	.byte $ff,$08
	.word @ref56
	.byte $ff,$08
	.word @ref56
	.byte $ff,$08
	.word @ref56
	.byte $ff,$06
	.word @ref59
	.byte $ff,$0f
	.word @ref60
	.byte $ff,$0f
	.word @ref61
@ref182:
	.byte $bf
@ref183:
	.byte $bf
	.byte $ff,$08
	.word @ref64
	.byte $ff,$08
	.word @ref56
	.byte $ff,$08
	.word @ref56
	.byte $ff,$06
	.word @ref59
	.byte $ff,$0f
	.word @ref60
	.byte $ff,$0f
	.word @ref61
@ref190:
	.byte $bf
@ref191:
	.byte $bf
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
	.byte $ff,$11
	.word @ref72
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref216:
	.byte $bf
@ref217:
	.byte $bf
@ref218:
	.byte $bf
@ref219:
	.byte $bf
@ref220:
	.byte $bf
@ref221:
	.byte $bf
@ref222:
	.byte $bf
@ref223:
	.byte $bf
@ref224:
	.byte $bf
@ref225:
	.byte $bf
@ref226:
	.byte $bf
@ref227:
	.byte $bf
@ref228:
	.byte $bf
@ref229:
	.byte $bf
@ref230:
	.byte $bf
@ref231:
	.byte $bf
@ref232:
	.byte $bf
@ref233:
	.byte $bf
@ref234:
	.byte $bf
@ref235:
	.byte $bf
@ref236:
	.byte $bf
@ref237:
	.byte $bf
@ref238:
	.byte $bf
@ref239:
	.byte $bf
	.byte $fd
	.word @song1ch4loop